name: CD - Deploy to Staging

on:
  workflow_run:
    workflows:
      - "CI - Build & Push Docker Image"
    types:
      - completed
    branches:
      - staging

jobs:
  deploy:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG_STAGING }}" > ~/.kube/config

      - name: Deploy
        run: |
          kubectl rollout restart deployment/telegram-mini-frontend -n staging
          kubectl rollout status deployment/telegram-mini-frontend -n staging
